# Generated by Django 4.2.11 on 2024-03-29 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('book_title', models.CharField(max_length=200)),
                ('book_author', models.CharField(max_length=100)),
                ('book_genre', models.CharField(choices=[('CLASSICS', 'Classics'), ('CRIME', 'Crime'), ('FANTASY', 'Fantasy'), ('GENERAL_FICTION', 'General Fiction'), ('HORROR', 'Horror'), ('NONFICTION', 'Nonfiction'), ('ROMANCE', 'Romance'), ('SCIENCE_FICTION', 'Science Fiction'), ('YOUNG_ADULT', 'Young Adult')], max_length=50)),
                ('book_blurb', models.TextField()),
                ('book_rating', models.IntegerField(choices=[('ONE', 1), ('TWO', 2), ('THREE', 3), ('FOUR', 4), ('FIVE', 5)])),
                ('book_review', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
