# Generated by Django 4.2.11 on 2024-03-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_bookreview_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='book_rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
