# Generated by Django 4.2.11 on 2024-03-30 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookreview',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
    ]
