# Generated by Django 4.2.11 on 2024-04-14 20:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_alter_bookreview_options_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='book_cover',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
