# Generated by Django 4.2.11 on 2024-04-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_alter_bookreview_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='book_genre',
            field=models.CharField(choices=[('CLASSICS', 'Classics'), ('CRIME', 'Crime'), ('FANTASY', 'Fantasy'), ('GENERAL FICTION', 'General Fiction'), ('HORROR', 'Horror'), ('NONFICTION', 'Nonfiction'), ('ROMANCE', 'Romance'), ('SCIENCE FICTION', 'Science Fiction'), ('YOUNG_ADULT', 'Young Adult')], max_length=50),
        ),
    ]
