# Generated by Django 4.2.11 on 2024-04-22 20:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_alter_bookreview_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='book_blurb',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='book_review',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
