# Generated by Django 4.2.11 on 2024-04-17 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='reviewer',
            new_name='user_profile',
        ),
    ]
